<a href="https://colab.research.google.com/github/ravichu/Lab6_Numpy_Pandas/blob/main/lab6_numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]


In [40]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)

Years + 5: [ 6  8 10 12 15]
Years * 2: [ 2  6 10 14 20]
Dot Product: 32


In [41]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2])

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [60 90]
Last year of experience: 10


In [42]:
# Step 1: Reshape 1D array into 2x3 matrix
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]


In [43]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]]


In [44]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))

Mean experience: 5.2
Std deviation of experience: 3.1240998703626617
Max salary: 100 Min salary: 50
Sum of all salaries: 450


In [45]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270]


In [46]:
# Step 1: Import pandas
import pandas as pd

# Step 2: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 3: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 4: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 5: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())

Generated Data:
     X   Y   Z
0   9   6  47
1   8  41   1
2  46  43  20
3  40   9  39
4  30  29  29
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0   9   6  47  2.197225  2.449490
1   8  41   1  2.079442  6.403124
2  46  43  20  3.828641  6.557439
3  40   9  39  3.688879  3.000000
4  30  29  29  3.401197  5.385165
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.152154  0.130955  0.988597  0.175019
Y       0.152154  1.000000 -0.891256  0.101280  0.996352
Z       0.130955 -0.891256  1.000000  0.185864 -0.885662
Log_X   0.988597  0.101280  0.185864  1.000000  0.135224
Sqrt_Y  0.175019  0.996352 -0.885662  0.135224  1.000000


In [47]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0   9   6  47  2.197225  2.449490
1   8  41   1  2.079442  6.403124
2  46  43  20  3.828641  6.557439
3  40   9  39  3.688879  3.000000
4  30  29  29  3.401197  5.385165
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   26.600000  25.600000  27.200000  3.039077  4.759043
std    17.487138  17.401149  17.838161  0.837616  1.920776
min     8.000000   6.000000   1.000000  2.079442  2.449490
25%     9.000000   9.000000  20.000000  2.197225  3.000000
50%    30.000000  29.000000  29.000000  3.401197  5.385165
75%    40.000000  41.000000  39.000000  3.688879  6.403124
max    46.000000  43.000000  47.000000  3.828641  6.557439
Column Means:
 X         26.600000
Y         25.600000
Z         27.200000
Log_X      3.039077
Sqrt_Y     4.759043
dtype: float64
Column Standard Deviations:
 X         17.487138
Y         1

In [48]:
# Step 1: Load dataset (use your file if available)
# df_kaggle = pd.read_csv('survey_results_public.csv')

# Sample fallback data
df_kaggle = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'YearsCodePro': [2, 10, 15, 5, 8],
    'ConvertedComp': [50000, 120000, 140000, 70000, 90000]
})
print("Loaded Dataset:\n", df_kaggle.head())

# Step 2: Select relevant columns
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data
df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Categorize experience
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group data and compute average salary
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedComp'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

# Step 6: Reset index
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())

Loaded Dataset:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master             8          90000
Subset of Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master             8          90000
Cleaned Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master         

TRY IT VERSION

In [49]:
# Step 1: Import NumPy
import numpy as np

# Step 2: Create a 1D array representing years of experience
years_exp = np.array([1, 3, 5, 7, 10])
print("Years of Experience:", years_exp)

# Step 3: Create a 2D array representing sample salaries (in thousands)
salaries = np.array([[50, 60, 70], [80, 90, 100]])
print("Salary Matrix:\n", salaries)

# Step 4: Create an array of zeros and ones for placeholder analysis
zeros_array = np.zeros((2, 2))
ones_array = np.ones((2, 3))
print("Zeros Array:\n", zeros_array)
print("Ones Array:\n", ones_array)

# Add 2 more data points
years_exp = np.append(years_exp, [12, 15])
print("Updated Years:", years_exp)

# Add new salary row
salaries = np.append(salaries, [[110, 120, 130]], axis=0)
print("Updated Salaries:\n", salaries)

# Create 3x3 identity matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

Years of Experience: [ 1  3  5  7 10]
Salary Matrix:
 [[ 50  60  70]
 [ 80  90 100]]
Zeros Array:
 [[0. 0.]
 [0. 0.]]
Ones Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Updated Years: [ 1  3  5  7 10 12 15]
Updated Salaries:
 [[ 50  60  70]
 [ 80  90 100]
 [110 120 130]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
# Step 1: Element-wise addition
exp_plus_5 = years_exp + 5
print("Years + 5:", exp_plus_5)

# Step 2: Element-wise multiplication
exp_times_2 = years_exp * 2
print("Years * 2:", exp_times_2)

# Step 3: Dot product (simulate salary projections)
sample1 = np.array([1, 2, 3])
sample2 = np.array([4, 5, 6])
dot_result = np.dot(sample1, sample2)
print("Dot Product:", dot_result)
print("Subtraction:", years_exp - 2)
print("Division:", years_exp / 2)
print("Exponential:", np.exp(years_exp))
print("Logarithm:", np.log(years_exp))

Years + 5: [ 6  8 10 12 15 17 20]
Years * 2: [ 2  6 10 14 20 24 30]
Dot Product: 32
Subtraction: [-1  1  3  5  8 10 13]
Division: [0.5 1.5 2.5 3.5 5.  6.  7.5]
Exponential: [2.71828183e+00 2.00855369e+01 1.48413159e+02 1.09663316e+03
 2.20264658e+04 1.62754791e+05 3.26901737e+06]
Logarithm: [0.         1.09861229 1.60943791 1.94591015 2.30258509 2.48490665
 2.7080502 ]


In [51]:
# Step 1: Access individual element
print("First year of experience:", years_exp[0])

# Step 2: Slice arrays
print("First two salaries:", salaries[0, :2])

# Step 3: Access all rows for a specific column
print("Second column salaries:", salaries[:, 1])

# Step 4: Negative indexing
print("Last year of experience:", years_exp[-1])
print("Reversed years:", years_exp[::-1])
print("Salary subset:\n", salaries[:, :2])

First year of experience: 1
First two salaries: [50 60]
Second column salaries: [ 60  90 120]
Last year of experience: 15
Reversed years: [15 12 10  7  5  3  1]
Salary subset:
 [[ 50  60]
 [ 80  90]
 [110 120]]


In [52]:
# Step 1: Reshape 1D array into 2x3 matrix
reshaped_exp = np.reshape(np.arange(1, 7), (2, 3))
print("Reshaped Experience Array:\n", reshaped_exp)

# Step 2: Flatten 2D arrays back into 1D
flattened_exp = reshaped_exp.flatten()
print("Flattened Array:", flattened_exp)

# Step 3: Transpose example
print("Transposed Array:\n", reshaped_exp.T)
reshaped_alt = np.reshape(np.arange(1, 13), (3, 4))
print("Alternative reshape:\n", reshaped_alt)

Reshaped Experience Array:
 [[1 2 3]
 [4 5 6]]
Flattened Array: [1 2 3 4 5 6]
Transposed Array:
 [[1 4]
 [2 5]
 [3 6]]
Alternative reshape:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [53]:
# Step 1: Add a bonus array to salaries using broadcasting
bonus = np.array([5, 10, 15])
salaries_with_bonus = salaries + bonus
print("Salaries after bonus:\n", salaries_with_bonus)
print("Scaled salaries:\n", salaries * 1.1)

Salaries after bonus:
 [[ 55  70  85]
 [ 85 100 115]
 [115 130 145]]
Scaled salaries:
 [[ 55.  66.  77.]
 [ 88.  99. 110.]
 [121. 132. 143.]]


In [54]:
# Step 1: Mean of years of experience
print("Mean experience:", np.mean(years_exp))

# Step 2: Standard deviation of experience
print("Std deviation of experience:", np.std(years_exp))

# Step 3: Max and Min salaries
print("Max salary:", np.max(salaries), "Min salary:", np.min(salaries))

# Step 4: Sum of salaries
print("Sum of all salaries:", np.sum(salaries))
print("Median:", np.median(years_exp))
print("Percentiles:", np.percentile(years_exp, [25, 50, 75]))

Mean experience: 7.571428571428571
Std deviation of experience: 4.655477353371521
Max salary: 130 Min salary: 50
Sum of all salaries: 810
Median: 7.0
Percentiles: [ 4.  7. 11.]


In [55]:
# Step 1: Apply trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
print("Sine of angles:", np.sin(angles))
print("Cosine of angles:", np.cos(angles))

# Step 2: Apply function along rows
salary_sums = np.apply_along_axis(np.sum, 1, salaries)
print("Sum of Salaries per person:", salary_sums)
print("Square root:", np.sqrt(years_exp))
print("Log transform:", np.log(years_exp))

Sine of angles: [0.         0.70710678 1.        ]
Cosine of angles: [1.00000000e+00 7.07106781e-01 6.12323400e-17]
Sum of Salaries per person: [180 270 360]
Square root: [1.         1.73205081 2.23606798 2.64575131 3.16227766 3.46410162
 3.87298335]
Log transform: [0.         1.09861229 1.60943791 1.94591015 2.30258509 2.48490665
 2.7080502 ]


In [56]:
# Step 1: Import pandas
import pandas as pd

# Step 2: Create a NumPy array of random data
data = np.random.randint(1, 50, size=(5, 3))

# Step 3: Convert the array into a DataFrame
df_data = pd.DataFrame(data, columns=['X', 'Y', 'Z'])
print("Generated Data:\n", df_data)

# Step 4: Apply NumPy functions to DataFrame columns
df_data['Log_X'] = np.log(df_data['X'])
df_data['Sqrt_Y'] = np.sqrt(df_data['Y'])
print("DataFrame with NumPy Transformations:\n", df_data)

# Step 5: Analyze data using Pandas correlation
print("Correlation Matrix:\n", df_data.corr())
print("Mean of columns:\n", df_data.mean())
print("Median of columns:\n", df_data.median())

Generated Data:
     X   Y   Z
0  43   2  11
1  15   7  23
2   9   5  17
3  47  46  37
4  40  36  46
DataFrame with NumPy Transformations:
     X   Y   Z     Log_X    Sqrt_Y
0  43   2  11  3.761200  1.414214
1  15   7  23  2.708050  2.645751
2   9   5  17  2.197225  2.236068
3  47  46  37  3.850148  6.782330
4  40  36  46  3.688879  6.000000
Correlation Matrix:
                X         Y         Z     Log_X    Sqrt_Y
X       1.000000  0.621487  0.419317  0.990393  0.545308
Y       0.621487  1.000000  0.899332  0.599700  0.993529
Z       0.419317  0.899332  1.000000  0.438757  0.935676
Log_X   0.990393  0.599700  0.438757  1.000000  0.531147
Sqrt_Y  0.545308  0.993529  0.935676  0.531147  1.000000
Mean of columns:
 X         30.800000
Y         19.200000
Z         26.800000
Log_X      3.241100
Sqrt_Y     3.815673
dtype: float64
Median of columns:
 X         40.000000
Y          7.000000
Z         23.000000
Log_X      3.688879
Sqrt_Y     2.645751
dtype: float64


In [57]:
# Step 1: Save the DataFrame to a CSV file
df_data.to_csv('sample_data.csv', index=False)
print("Data saved to 'sample_data.csv'.")

# Step 2: Load the CSV file
df_imported = pd.read_csv('sample_data.csv')
print("Imported DataFrame:\n", df_imported)

# Step 3: Generate summary statistics
summary_stats = df_imported.describe()
print("Summary Statistics:\n", summary_stats)

# Step 4: Display column means and standard deviations
print("Column Means:\n", df_imported.mean())
print("Column Standard Deviations:\n", df_imported.std())
df_imported['Sum_XY'] = df_imported['X'] + df_imported['Y']
print("Updated DataFrame:\n", df_imported)

Data saved to 'sample_data.csv'.
Imported DataFrame:
     X   Y   Z     Log_X    Sqrt_Y
0  43   2  11  3.761200  1.414214
1  15   7  23  2.708050  2.645751
2   9   5  17  2.197225  2.236068
3  47  46  37  3.850148  6.782330
4  40  36  46  3.688879  6.000000
Summary Statistics:
                X          Y          Z     Log_X    Sqrt_Y
count   5.000000   5.000000   5.000000  5.000000  5.000000
mean   30.800000  19.200000  26.800000  3.241100  3.815673
std    17.469974  20.290392  14.429137  0.744273  2.408486
min     9.000000   2.000000  11.000000  2.197225  1.414214
25%    15.000000   5.000000  17.000000  2.708050  2.236068
50%    40.000000   7.000000  23.000000  3.688879  2.645751
75%    43.000000  36.000000  37.000000  3.761200  6.000000
max    47.000000  46.000000  46.000000  3.850148  6.782330
Column Means:
 X         30.800000
Y         19.200000
Z         26.800000
Log_X      3.241100
Sqrt_Y     3.815673
dtype: float64
Column Standard Deviations:
 X         17.469974
Y         2

In [58]:
# Step 1: Load dataset (use your file if available)
# df_kaggle = pd.read_csv('survey_results_public.csv')

# Sample fallback data
df_kaggle = pd.DataFrame({
    'Country': ['Philippines', 'USA', 'UK', 'Canada', 'Germany'],
    'EdLevel': ['Bachelor', 'Master', 'PhD', 'Bachelor', 'Master'],
    'YearsCodePro': [2, 10, 15, 5, 8],
    'ConvertedComp': [50000, 120000, 140000, 70000, 90000]
})
print("Loaded Dataset:\n", df_kaggle.head())

# Step 2: Select relevant columns
df_subset = df_kaggle[['Country', 'EdLevel', 'YearsCodePro', 'ConvertedComp']]
print("Subset of Data:\n", df_subset.head())

# Step 3: Clean the data
df_clean = df_subset.dropna()
print("Cleaned Data:\n", df_clean.head())

# Step 4: Categorize experience
df_clean['ExperienceLevel'] = np.where(df_clean['YearsCodePro'] >= 10, 'Senior', 'Junior')

# Step 5: Group data and compute average salary
grouped_data = df_clean.groupby(['Country', 'ExperienceLevel'])['ConvertedComp'].mean()
print("Grouped Average Salary:\n", grouped_data.head())

# Step 6: Reset index
grouped_data = grouped_data.reset_index()
print("Formatted Grouped Data:\n", grouped_data.head())
group_edlevel = df_clean.groupby('EdLevel')['ConvertedComp'].mean()
print("Grouped by Education:\n", group_edlevel)

Loaded Dataset:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master             8          90000
Subset of Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master             8          90000
Cleaned Data:
        Country   EdLevel  YearsCodePro  ConvertedComp
0  Philippines  Bachelor             2          50000
1          USA    Master            10         120000
2           UK       PhD            15         140000
3       Canada  Bachelor             5          70000
4      Germany    Master         