<a href="https://colab.research.google.com/github/ravichu/Lab6_Numpy_Pandas/blob/main/LAB_6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Laboratory 6")

Laboratory 6


In [2]:
import numpy as np
import pandas as pd

In [3]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
data = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
print(f"{STUDENT_NAME}'s Array:", data)

mean_val = np.mean(data)
std_val = np.std(data)
print("Mean:", mean_val, "Std Dev:", std_val)

KIM HARRIE PILAPIL BEJAR's Array: [  6  77  77   6  57  21  21  60 102  42]
Mean: 46.9 Std Dev: 31.357455253894567


In [4]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
matrix = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))
print(f"{STUDENT_NAME}'s Matrix:\n", matrix)

row_sums = np.sum(matrix, axis=1)
col_sums = np.sum(matrix, axis=0)
print("Row sums:", row_sums)
print("Column sums:", col_sums)

KIM HARRIE PILAPIL BEJAR's Matrix:
 [[ 6 13 13  6]
 [21 21 38 42]
 [13 15 13 20]]
Row sums: [ 38 122  61]
Column sums: [40 49 64 68]


In [5]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
arr3d = np.random.randint(0, STUDENT_ID % 20 + 10, size=(3,3,3))
print(f"{STUDENT_NAME}'s 3D Array:\n", arr3d)

slice_mid = arr3d[:,1,:]
print("Slice[:,1,:]:\n", slice_mid)

KIM HARRIE PILAPIL BEJAR's 3D Array:
 [[[ 5 12 12]
  [ 5 24 20]
  [20  5  9]]

 [[25 23 12]
  [16 14 12]
  [18 23 19]]

 [[ 3 22  8]
  [26  2  2]
  [ 6 13 16]]]
Slice[:,1,:]:
 [[ 5 24 20]
 [16 14 12]
 [26  2  2]]


In [6]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
x = np.random.randint(1, STUDENT_ID % 100 + 50, size=10)
filtered = x[(x>STUDENT_ID%50) & (x<STUDENT_ID%100)]

print(f"{STUDENT_NAME}'s Original:", x)
print("Filtered subset:", filtered)

KIM HARRIE PILAPIL BEJAR's Original: [  6  77  77   6  57  21  21  60 102  42]
Filtered subset: [57 60 42]


In [7]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
A = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))
B = np.random.randint(1, STUDENT_ID % 50 + 20, size=(2,2))

print("Matrix A:\n", A)
print("Matrix B:\n", B)

product = A @ B
det_A = np.linalg.det(A)

print("A @ B:\n", product)
print("Determinant of A:", det_A)

Matrix A:
 [[ 6 13]
 [13  6]]
Matrix B:
 [[21 21]
 [38 42]]
A @ B:
 [[620 672]
 [501 525]]
Determinant of A: -133.0


In [8]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

angles = np.linspace(0, 2*np.pi, 8)
sine_vals = np.sin(angles)
cos_vals = np.cos(angles)

print(f"{STUDENT_NAME}'s Angles:", angles)
print("Sine:", sine_vals)
print("Cosine:", cos_vals)

KIM HARRIE PILAPIL BEJAR's Angles: [0.         0.8975979  1.7951958  2.6927937  3.5903916  4.48798951
 5.38558741 6.28318531]
Sine: [ 0.00000000e+00  7.81831482e-01  9.74927912e-01  4.33883739e-01
 -4.33883739e-01 -9.74927912e-01 -7.81831482e-01 -2.44929360e-16]
Cosine: [ 1.          0.6234898  -0.22252093 -0.90096887 -0.90096887 -0.22252093
  0.6234898   1.        ]


In [9]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(4,4))
arr[::2, ::2] = 0

print(f"{STUDENT_NAME}'s Modified 4x4 Array:\n", arr)

KIM HARRIE PILAPIL BEJAR's Modified 4x4 Array:
 [[ 0 13  0  6]
 [21 21 38 42]
 [ 0 15  0 20]
 [29 36  9 35]]


In [10]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
scores = np.random.randint(0, STUDENT_ID % 100 + 50, 10)
grades = np.where(scores>=STUDENT_ID%70,'Pass','Fail')

print(f"{STUDENT_NAME}'s Scores:", scores)
print("Grades:", grades)

KIM HARRIE PILAPIL BEJAR's Scores: [  5  76  76   5  56  20  20  59 101  41]
Grades: ['Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Fail']


In [11]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, size=(3,4))

flat_arr = arr.flatten()
transposed_arr = arr.T

print("Original array:\n", arr)
print("Flattened:", flat_arr)
print("Transposed:\n", transposed_arr)

Original array:
 [[ 6 13 13  6]
 [21 21 38 42]
 [13 15 13 20]]
Flattened: [ 6 13 13  6 21 21 38 42 13 15 13 20]
Transposed:
 [[ 6 21 13]
 [13 21 15]
 [13 38 13]
 [ 6 42 20]]


In [12]:
import numpy as np
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
arr = np.random.randint(1, STUDENT_ID % 50 + 20, (3,3))

mask = arr % 2 == 0
arr[mask] = -1

print("Array with conditional replacements:\n", arr)

Array with conditional replacements:
 [[-1 13 13]
 [-1 21 21]
 [-1 -1 13]]


In [13]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name': [STUDENT_NAME]*5,
    'Score': np.random.randint(STUDENT_ID%50, STUDENT_ID%100+50,5),
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})

print(df)

                       Name  Score  YearsCodePro
0  KIM HARRIE PILAPIL BEJAR     32            20
1  KIM HARRIE PILAPIL BEJAR    103            20
2  KIM HARRIE PILAPIL BEJAR    103             5
3  KIM HARRIE PILAPIL BEJAR     32             9
4  KIM HARRIE PILAPIL BEJAR     83            25


In [14]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel': ['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

avg_salary = df.groupby('EdLevel')['ConvertedComp'].mean()
print(avg_salary)

EdLevel
Bachelor    129413.0
Master       97666.0
PhD          78092.0
Name: ConvertedComp, dtype: float64


In [15]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top5 = df.sort_values(by='ConvertedComp', ascending=False)
print(top5)

       Country  ConvertedComp
0  Philippines         144325
3       Canada         114501
4      Germany         104824
1          USA          90508
2           UK          78092


In [16]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Name':[STUDENT_NAME]*5,
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10,5)
})

high_exp = df[df['YearsCodePro']>STUDENT_ID%10]
print(high_exp)

                       Name  YearsCodePro
1  KIM HARRIE PILAPIL BEJAR            12
2  KIM HARRIE PILAPIL BEJAR            12
4  KIM HARRIE PILAPIL BEJAR            24


In [17]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,150000,5)})

bins = [0, 50000, 100000, 150000, 200000]
labels = ['0-50k', '50-100k', '100-150k', '>150k']

df['Bracket'] = pd.cut(df['ConvertedComp'], bins=bins, labels=labels)
print(df)

   ConvertedComp   Bracket
0         144325  100-150k
1          90508   50-100k
2          78092   50-100k
3         114501  100-150k
4         104824  100-150k


In [18]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,150000,5)})

df['LogComp'] = np.log(df['ConvertedComp'])
print(df)

   ConvertedComp    LogComp
0         144325  11.879823
1          90508  11.413194
2          78092  11.265643
3         114501  11.648339
4         104824  11.560038


In [19]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'YearsCodePro': np.random.randint(0, STUDENT_ID%20+10, 5),
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

corr_matrix = df.corr()
print(corr_matrix)

               YearsCodePro  ConvertedComp
YearsCodePro       1.000000      -0.613956
ConvertedComp     -0.613956       1.000000


In [20]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'EdLevel':['Bachelor','Master','PhD','Bachelor','Master'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

summary = df.groupby('EdLevel')['ConvertedComp'].agg(['mean','median','std']).reset_index()
print(summary)

    EdLevel      mean    median           std
0  Bachelor  129413.0  129413.0  21088.752642
1    Master   97666.0   97666.0  10122.940679
2       PhD   78092.0   78092.0           NaN


In [21]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({'ConvertedComp': np.random.randint(40000,150000,5)})

threshold = 110000
df['HighPay'] = np.where(df['ConvertedComp'] > threshold, 'Yes', 'No')

print(df)

   ConvertedComp HighPay
0         144325     Yes
1          90508      No
2          78092      No
3         114501     Yes
4         104824      No


In [22]:
import numpy as np
import pandas as pd
STUDENT_NAME = "KIM HARRIE PILAPIL BEJAR"
STUDENT_ID = 20250077

np.random.seed(STUDENT_ID)
df = pd.DataFrame({
    'Country': ['Philippines','USA','UK','Canada','Germany'],
    'ConvertedComp': np.random.randint(40000, 150000, 5)
})

top_countries = df.groupby('Country')['ConvertedComp'].agg(['mean','max'])
print(top_countries)

                 mean     max
Country                      
Canada       114501.0  114501
Germany      104824.0  104824
Philippines  144325.0  144325
UK            78092.0   78092
USA           90508.0   90508
